<a href="https://colab.research.google.com/github/Shitalsin/Python/blob/main/Assignment3_Shital.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files.upload()

Saving Country-data.csv to Country-data.csv

{'Country-data.csv': b'country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp\r\nAfghanistan,90.2,10,7.58,44.9,1610,9.44,56.2,5.82,553\r\nAlbania,16.6,28,6.55,48.6,9930,4.49,76.3,1.65,4090\r\nAlgeria,27.3,38.4,4.17,31.4,12900,16.1,76.5,2.89,4460\r\nAngola,119,62.3,2.85,42.9,5900,22.4,60.1,6.16,3530\r\nAntigua and Barbuda,10.3,45.5,6.03,58.9,19100,1.44,76.8,2.13,12200\r\nArgentina,14.5,18.9,8.1,16,18700,20.9,75.8,2.37,10300\r\nArmenia,18.1,20.8,4.4,45.3,6700,7.77,73.3,1.69,3220\r\nAustralia,4.8,19.8,8.73,20.9,41400,1.16,82,1.93,51900\r\nAustria,4.3,51.3,11,47.8,43200,0.873,80.5,1.44,46900\r\nAzerbaijan,39.2,54.3,5.88,20.7,16000,13.8,69.1,1.92,5840\r\nBahamas,13.8,35,7.89,43.7,22900,-0.393,73.8,1.86,28000\r\nBahrain,8.6,69.5,4.97,50.9,41100,7.44,76,2.16,20700\r\nBangladesh,49.4,16,3.52,21.8,2440,7.14,70.4,2.33,758\r\nBarbados,14.2,39.5,7.97,48.7,15300,0.321,76.7,1.78,16000\r\nBelarus,5.5,51.4,5.61,64.5,16200,15.1,70.4,1.49,6030\r\nBelgium,4.5,76.4,10.7,74.7,41100,1.88,80,1.86,44400\r\nBelize,18.8,58.2,5.2,57.5,7880,1.14,71.4,2.71,4340\r\nBenin,111,23.8,4.1,37.2,1820,0.885,61.8,5.36,758\r\nBhutan,42.7,42.5,5.2,70.7,6420,5.99,72.1,2.38,2180\r\nBolivia,46.6,41.2,4.84,34.3,5410,8.78,71.6,3.2,1980\r\nBosnia and Herzegovina,6.9,29.7,11.1,51.3,9720,1.4,76.8,1.31,4610\r\nBotswana,52.5,43.6,8.3,51.3,13300,8.92,57.1,2.88,6350\r\nBrazil,19.8,10.7,9.01,11.8,14500,8.41,74.2,1.8,11200\r\nBrunei,10.5,67.4,2.84,28,80600,16.7,77.1,1.84,35300\r\nBulgaria,10.8,50.2,6.87,53,15300,1.11,73.9,1.57,6840\r\nBurkina Faso,116,19.2,6.74,29.6,1430,6.81,57.9,5.87,575\r\nBurundi,93.6,8.92,11.6,39.2,764,12.3,57.7,6.26,231\r\nCambodia,44.4,54.1,5.68,59.5,2520,3.12,66.1,2.88,786\r\nCameroon,108,22.2,5.13,27,2660,1.91,57.3,5.11,1310\r\nCanada,5.6,29.1,11.3,31,40700,2.87,81.3,1.63,47400\r\nCape Verde,26.5,32.7,4.09,61.8,5830,0.505,72.5,2.67,3310\r\nCentral African Republic,149,11.8,3.98,26.5,888,2.01,47.5,5.21,446\r\nChad,150,36.8,4.53,43.5,1930,6.39,56.5,6.59,897\r\nChile,8.7,37.7,7.96,31.3,19400,8.96,79.1,1.88,12900\r\nChina,15.7,26.3,5.07,22.6,9530,6.94,74.6,1.59,4560\r\nColombia,18.6,15.9,7.59,17.8,10900,3.86,76.4,2.01,6250\r\nComoros,88.2,16.5,4.51,51.7,1410,3.87,65.9,4.75,769\r\n"Congo, Dem. Rep.",116,41.1,7.91,49.6,609,20.8,57.5,6.54,334\r\n"Congo, Rep.",63.9,85.1,2.46,54.7,5190,20.7,60.4,4.95,2740\r\nCosta Rica,10.2,33.2,10.9,35,13000,6.57,80.4,1.92,8200\r\nCote d\'Ivoire,111,50.6,5.3,43.3,2690,5.39,56.3,5.27,1220\r\nCroatia,5.5,37.6,7.76,38.1,20100,0.821,76.3,1.55,13500\r\nCyprus,3.6,50.2,5.97,57.5,33900,2.01,79.9,1.42,30800\r\nCzech Republic,3.4,66,7.88,62.9,28300,-1.43,77.5,1.51,19800\r\nDenmark,4.1,50.5,11.4,43.6,44000,3.22,79.5,1.87,58000\r\nDominican Republic,34.4,22.7,6.22,33.3,11100,5.44,74.6,2.6,5450\r\nEcuador,25.1,27.9,8.06,32.4,9350,7.47,76.7,2.66,4660\r\nEgypt,29.1,21.3,4.66,26.6,9860,10.1,70.5,3.19,2600\r\nEl Salvador,19.2,26.9,6.91,46.6,7300,2.65,74.1,2.27,2990\r\nEquatorial Guinea,111,85.8,4.48,58.9,33700,24.9,60.9,5.21,17100\r\nEritrea,55.2,4.79,2.66,23.3,1420,11.6,61.7,4.61,482\r\nEstonia,4.5,75.1,6.03,68.7,22700,1.74,76,1.72,14600\r\nFiji,24.1,57.8,4.86,63.9,7350,4.23,65.3,2.67,3650\r\nFinland,3,38.7,8.95,37.4,39800,0.351,80,1.87,46200\r\nFrance,4.2,26.8,11.9,28.1,36900,1.05,81.4,2.03,40600\r\nGabon,63.7,57.7,3.5,18.9,15400,16.6,62.9,4.08,8750\r\nGambia,80.3,23.8,5.69,42.7,1660,4.3,65.5,5.71,562\r\nGeorgia,16.5,35,10.1,52.8,6730,8.55,72.8,1.92,2960\r\nGermany,4.2,42.3,11.6,37.1,40400,0.758,80.1,1.39,41800\r\nGhana,74.7,29.5,5.22,45.9,3060,16.6,62.2,4.27,1310\r\nGreece,3.9,22.1,10.3,30.7,28700,0.673,80.4,1.48,26900\r\nGrenada,14.6,23.8,5.86,49.2,11200,0.48,71.3,2.24,7370\r\nGuatemala,35.4,25.8,6.85,36.3,6710,5.14,71.3,3.38,2830\r\nGuinea,109,30.3,4.93,43.2,1190,16.1,58,5.34,648\r\nGuinea-Bissau,114,14.9,8.5,35.2,1390,2.97,55.6,5.05,547\r\nGuyana,37.6,51.4,5.38,79.1,5840,5.73,65.5,2.65,3040\r\nHaiti,208,15.3,6.91,64.7,1500,5.45,32.1,3.33,662\r\nHungary,6,81.8,7.33,76.5,22300,2.33,74.5,1.25,13100\r\nIceland,2.6,53.4,9.4,43.3,38800,5.47,82,2.2,41900\r\nIndia,58.8,22.6,4.05,27.1,4410,8.98,66.2,2.6,1350\r\nIndonesia,33.3,24.3,2.61,22.4,8430,15.3,69.9,2.48,3110\r\nIran,19.3,24.4,5.6,19.4,17400,15.9,74.5,1.76,6530\r\nIraq,36.9,39.4,8.41,34.1,12700,16.6,67.2,4.56,4500\r\nIreland,4.2,103,9.19,86.5,45700,-3.22,80.4,2.05,48700\r\nIsrael,4.6,35,7.63,32.9,29600,1.77,81.4,3.03,30600\r\nItaly,4,25.2,9.53,27.2,36200,0.319,81.7,1.46,35800\r\nJamaica,18.1,31.3,4.81,49.6,8000,9.81,74.7,2.17,4680\r\nJapan,3.2,15,9.49,13.6,35800,-1.9,82.8,1.39,44500\r\nJordan,21.1,48.3,8.04,69,9470,8.43,75.8,3.66,3680\r\nKazakhstan,21.5,44.2,4.29,29.9,20100,19.5,68.4,2.6,9070\r\nKenya,62.2,20.7,4.75,33.6,2480,2.09,62.8,4.37,967\r\nKiribati,62.7,13.3,11.3,79.9,1730,1.52,60.7,3.84,1490\r\nKuwait,10.8,66.7,2.63,30.4,75200,11.2,78.2,2.21,38500\r\nKyrgyz Republic,29.6,51.6,6.18,81.7,2790,10,68.5,3.1,880\r\nLao,78.9,35.4,4.47,49.3,3980,9.2,63.8,3.15,1140\r\nLatvia,7.8,53.7,6.68,55.1,18300,-0.812,73.1,1.36,11300\r\nLebanon,10.3,35.8,7.03,60.2,16300,0.238,79.8,1.61,8860\r\nLesotho,99.7,39.4,11.1,101,2380,4.15,46.5,3.3,1170\r\nLiberia,89.3,19.1,11.8,92.6,700,5.47,60.8,5.02,327\r\nLibya,16.6,65.6,3.88,42.1,29600,14.2,76.1,2.41,12100\r\nLithuania,6.1,65.3,7.04,67.2,21100,2.38,73.2,1.5,12000\r\nLuxembourg,2.8,175,7.77,142,91700,3.62,81.3,1.63,105000\r\n"Macedonia, FYR",10.4,39.8,7.09,58.1,11400,2.04,74,1.47,4540\r\nMadagascar,62.2,25,3.77,43,1390,8.79,60.8,4.6,413\r\nMalawi,90.5,22.8,6.59,34.9,1030,12.1,53.1,5.31,459\r\nMalaysia,7.9,86.9,4.39,71,21100,7.27,74.5,2.15,9070\r\nMaldives,13.2,77.6,6.33,65.4,10500,2.88,77.9,2.23,7100\r\nMali,137,22.8,4.98,35.1,1870,4.37,59.5,6.55,708\r\nMalta,6.8,153,8.65,154,28300,3.83,80.3,1.36,21100\r\nMauritania,97.4,50.7,4.41,61.2,3320,18.9,68.2,4.98,1200\r\nMauritius,15,51.2,6,62.2,15900,1.13,73.4,1.57,8000\r\n"Micronesia, Fed. Sts.",40,23.5,14.2,81,3340,3.8,65.4,3.46,2860\r\nMoldova,17.2,39.2,11.7,78.5,3910,11.1,69.7,1.27,1630\r\nMongolia,26.1,46.7,5.44,56.7,7710,39.2,66.2,2.64,2650\r\nMontenegro,6.8,37,9.11,62.7,14000,1.6,76.4,1.77,6680\r\nMorocco,33.5,32.2,5.2,43,6440,0.976,73.5,2.58,2830\r\nMozambique,101,31.5,5.21,46.2,918,7.64,54.5,5.56,419\r\nMyanmar,64.4,0.109,1.97,0.0659,3720,7.04,66.8,2.41,988\r\nNamibia,56,47.8,6.78,60.7,8460,3.56,58.6,3.6,5190\r\nNepal,47,9.58,5.25,36.4,1990,15.1,68.3,2.61,592\r\nNetherlands,4.5,72,11.9,63.6,45500,0.848,80.7,1.79,50300\r\nNew Zealand,6.2,30.3,10.1,28,32300,3.73,80.9,2.17,33700\r\nNiger,123,22.2,5.16,49.1,814,2.55,58.8,7.49,348\r\nNigeria,130,25.3,5.07,17.4,5150,104,60.5,5.84,2330\r\nNorway,3.2,39.7,9.48,28.5,62300,5.95,81,1.95,87800\r\nOman,11.7,65.7,2.77,41.2,45300,15.6,76.1,2.9,19300\r\nPakistan,92.1,13.5,2.2,19.4,4280,10.9,65.3,3.85,1040\r\nPanama,19.7,70,8.1,78.2,15400,2.59,77.8,2.62,8080\r\nParaguay,24.1,55.1,5.87,51.5,7290,6.1,74.1,2.73,3230\r\nPeru,20.3,27.8,5.08,23.8,9960,5.71,77.9,2.54,5020\r\nPhilippines,31.9,34.8,3.61,36.6,5600,4.22,69,3.16,2130\r\nPoland,6,40.1,7.46,42.1,21800,1.66,76.3,1.41,12600\r\nPortugal,3.9,29.9,11,37.4,27200,0.643,79.8,1.39,22500\r\nQatar,9,62.3,1.81,23.8,125000,6.98,79.5,2.07,70300\r\nRomania,11.5,32.6,5.58,38.8,17800,3.53,73.7,1.59,8230\r\nRussia,10,29.2,5.08,21.1,23100,14.2,69.2,1.57,10700\r\nRwanda,63.6,12,10.5,30,1350,2.61,64.6,4.51,563\r\nSamoa,18.9,29.2,6.47,53.1,5400,1.72,71.5,4.34,3450\r\nSaudi Arabia,15.7,49.6,4.29,33,45400,17.2,75.1,2.96,19300\r\nSenegal,66.8,24.9,5.66,40.3,2180,1.85,64,5.06,1000\r\nSerbia,7.6,32.9,10.4,47.9,12700,5.88,74.7,1.4,5410\r\nSeychelles,14.4,93.8,3.4,108,20400,-4.21,73.4,2.17,10800\r\nSierra Leone,160,16.8,13.1,34.5,1220,17.2,55,5.2,399\r\nSingapore,2.8,200,3.96,174,72100,-0.046,82.7,1.15,46600\r\nSlovak Republic,7,76.3,8.79,77.8,25200,0.485,75.5,1.43,16600\r\nSlovenia,3.2,64.3,9.41,62.9,28700,-0.987,79.5,1.57,23400\r\nSolomon Islands,28.1,49.3,8.55,81.2,1780,6.81,61.7,4.24,1290\r\nSouth Africa,53.7,28.6,8.94,27.4,12000,6.35,54.3,2.59,7280\r\nSouth Korea,4.1,49.4,6.93,46.2,30400,3.16,80.1,1.23,22100\r\nSpain,3.8,25.5,9.54,26.8,32500,0.16,81.9,1.37,30700\r\nSri Lanka,11.2,19.6,2.94,26.8,8560,22.8,74.4,2.2,2810\r\nSt. Vincent and the Grenadines,20.7,26.9,4.47,57.1,9920,4.44,71.6,2.07,6230\r\nSudan,76.7,19.7,6.32,17.2,3370,19.6,66.3,4.88,1480\r\nSuriname,24.1,52.5,7.01,38.4,14200,7.2,70.3,2.52,8300\r\nSweden,3,46.2,9.63,40.7,42900,0.991,81.5,1.98,52100\r\nSwitzerland,4.5,64,11.5,53.3,55500,0.317,82.2,1.52,74600\r\nTajikistan,52.4,14.9,5.98,58.6,2110,12.5,69.6,3.51,738\r\nTanzania,71.9,18.7,6.01,29.1,2090,9.25,59.3,5.43,702\r\nThailand,14.9,66.5,3.88,60.8,13500,4.08,76.6,1.55,5080\r\nTimor-Leste,62.6,2.2,9.12,27.8,1850,26.5,71.1,6.23,3600\r\nTogo,90.3,40.2,7.65,57.3,1210,1.18,58.7,4.87,488\r\nTonga,17.4,12.4,5.07,60.3,4980,3.68,69.9,3.91,3550\r\nTunisia,17.4,50.5,6.21,55.3,10400,3.82,76.9,2.14,4140\r\nTurkey,19.1,20.4,6.74,25.5,18000,7.01,78.2,2.15,10700\r\nTurkmenistan,62,76.3,2.5,44.5,9940,2.31,67.9,2.83,4440\r\nUganda,81,17.1,9.01,28.6,1540,10.6,56.8,6.15,595\r\nUkraine,11.7,47.1,7.72,51.1,7820,13.4,70.4,1.44,2970\r\nUnited Arab Emirates,8.6,77.7,3.66,63.6,57600,12.5,76.5,1.87,35000\r\nUnited Kingdom,5.2,28.2,9.64,30.8,36200,1.57,80.3,1.92,38900\r\nUnited States,7.3,12.4,17.9,15.8,49400,1.22,78.7,1.93,48400\r\nUruguay,10.6,26.3,8.35,25.4,17100,4.91,76.4,2.08,11900\r\nUzbekistan,36.3,31.7,5.81,28.5,4240,16.5,68.8,2.34,1380\r\nVanuatu,29.2,46.6,5.25,52.7,2950,2.62,63,3.5,2970\r\nVenezuela,17.1,28.5,4.91,17.6,16500,45.9,75.4,2.47,13500\r\nVietnam,23.3,72,6.84,80.2,4490,12.1,73.1,1.95,1310\r\nYemen,56.3,30,5.18,34.4,4480,23.6,67.5,4.67,1310\r\nZambia,83.1,37,5.89,30.9,3280,14,52,5.4,1460\r\n'}

In [9]:
import pandas as pd

df = pd.read_csv("Country-data.csv")

df.head()

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
0,Afghanistan,90.2,10.0,7.58,44.9,1610,9.44,56.2,5.82,553
1,Albania,16.6,28.0,6.55,48.6,9930,4.49,76.3,1.65,4090
2,Algeria,27.3,38.4,4.17,31.4,12900,16.10,76.5,2.89,4460
3,Angola,119.0,62.3,2.85,42.9,5900,22.40,60.1,6.16,3530
4,Antigua and Barbuda,10.3,45.5,6.03,58.9,19100,1.44,76.8,2.13,12200

In [21]:
df.shape
df.info()
df.head()
df.isnull().sum()
df.duplicated().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     167 non-null    object
 1   child_mort  167 non-null    float64
 2   exports     167 non-null    float64
 3   health      167 non-null    float64
 4   imports     167 non-null    float64
 5   income      167 non-null    int64
 6   inflation   167 non-null    float64
 7   life_expec  167 non-null    float64
 8   total_fer   167 non-null    float64
 9   gdpp        167 non-null    int64
 10  Cluster     167 non-null    int32
dtypes: float64(7), int32(1), int64(2), object(1)
memory usage: 13.8+ KB

,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp,Cluster
count,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000
mean,38.270060,41.108976,6.815689,46.890215,17144.688623,7.781832,70.555689,2.947964,12964.155689,0.754491
std,40.328931,27.412010,2.746837,24.209589,19278.067698,10.570704,8.893172,1.513848,18328.704809,0.853533
min,2.600000,0.109000,1.810000,0.065900,609.000000,-4.210000,32.100000,1.150000,231.000000,0.000000
25%,8.250000,23.800000,4.920000,30.200000,3355.000000,1.810000,65.300000,1.795000,1330.000000,0.000000
50%,19.300000,35.000000,6.320000,43.300000,9960.000000,5.390000,73.100000,2.410000,4660.000000,0.000000
75%,62.100000,51.350000,8.600000,58.750000,22800.000000,10.750000,76.800000,3.880000,14050.000000,2.000000
max,208.000000,200.000000,17.900000,174.000000,125000.000000,104.000000,82.800000,7.490000,105000.000000,2.000000

In [12]:
df.describe()

,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
count,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000
mean,38.270060,41.108976,6.815689,46.890215,17144.688623,7.781832,70.555689,2.947964,12964.155689
std,40.328931,27.412010,2.746837,24.209589,19278.067698,10.570704,8.893172,1.513848,18328.704809
min,2.600000,0.109000,1.810000,0.065900,609.000000,-4.210000,32.100000,1.150000,231.000000
25%,8.250000,23.800000,4.920000,30.200000,3355.000000,1.810000,65.300000,1.795000,1330.000000
50%,19.300000,35.000000,6.320000,43.300000,9960.000000,5.390000,73.100000,2.410000,4660.000000
75%,62.100000,51.350000,8.600000,58.750000,22800.000000,10.750000,76.800000,3.880000,14050.000000
max,208.000000,200.000000,17.900000,174.000000,125000.000000,104.000000,82.800000,7.490000,105000.000000

In [16]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

df['Cluster'] = kmeans.fit_predict(X_scaled)

In [17]:
df[['country','Cluster']].head(10)

               country  Cluster
0          Afghanistan        2
1              Albania        0
2              Algeria        0
3               Angola        2
4  Antigua and Barbuda        0
5            Argentina        0
6              Armenia        0
7            Australia        1
8              Austria        1
9           Azerbaijan        0

In [26]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=1.5, min_samples=5)

df['DBSCAN'] = dbscan.fit_predict(X_scaled)
df[['country','DBSCAN']].head()

X = df.drop(['country','Cluster','DBSCAN'], axis=1)
y = df['Cluster']

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred_rf))

Accuracy: 1.0

In [31]:
!pip install xgboost
from xgboost import XGBClassifier
xgb= XGBClassifier()
xgb.fit(X_train,y_train)
pred_xgb= xgb.predict(X_test)
print("Accuracy: ", accuracy_score(y_test,pred_xgb))

print("Random Forest: ",accuracy_score(y_test,pred_rf))
print("XGBoost  : ",accuracy_score(y_test,pred_xgb))

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
Accuracy:  1.0
Random Forest:  1.0
XGBoost  :  1.0

In [33]:
df['Cluster'].value_counts()
df.groupby('Cluster')[['income','gdpp','life_expec']].mean()

               income          gdpp  life_expec
Cluster
0        12321.744186   6461.767442   72.566279
1        45672.222222  42494.444444   80.127778
2         3539.844444   1766.711111   59.055556